### PR TITLE
Fix: Add troubleshooting section for access error

### PR DESCRIPTION
**Pull request by norosa**
This commit identifies an issue some of our customers have experienced and recommends the fix we have used to resolve the issue in the past.

See also:

- https://stackoverflow.com/a/59931415

---

Edit: It looks like I messed up here, and most of the changes ended up being committed as a fixup on [a different pull request](https://github.com/doitintl/help/pull/173/files).

The changes on this PR are now essentially fixups for #173.

### CODE REVIEW

**Comment by norosa** [comment]
Preview of my new Troubleshooting entry here: https://deploy-preview-171--doitintl-help.netlify.app/docs/google-cloud/transfer-google-cloud-projects/transfer-manually#google-cloud-tells-me-i-dont-have-access-to-my-project-or-it-does-not-exist

**Comment by azure562** [comment]
Not sure whether the changes have been merged in another PR https://github.com/doitintl/help/pull/173/files ... there doesn't seem to be much information at https://github.com/doitintl/help/pull/171/files, maybe I'm missing something?

**Review by mikesparr — APPROVED** [review]
Based on the preview link with what I'm assuming is the change (enable Cloud Resource Manager API or use the gcloud command) it looks good to me.

I am not certain that's what I was reviewing though but preview looked good.

**Comment by norosa** [comment]
@qing Would you mind reviewing this PR, please? Mike has approved it as the CRE SME, so I think it's ready to go.

Please excuse my Git mistakes in splitting the changes across multiple branches. Not much I can do about that now, unfortunately. But merging this PR will close the loop on the whole change.

**Comment by norosa** [comment]
Thanks for the review @mikesparr. Looks like I accidentally added included this commit in the https://github.com/doitintl/help/pull/173, so the changes are already live. As a result, this PR is empty, and I will close now.

**Pull request closed without merging**
