### PR TITLE
docs: Link multiple projects

### PR DESCRIPTION
**Pull request by yuvaldrori**
Removed the documentation on how to link multiple projects to a billing account because people don't read the documentation and unintentionally link projects to the DoiT billing account.

### CODE REVIEW

**Comment by azure562** [comment]
@yuvaldrori can we explain the use case of linking multiple projects and make clear the consequence? Maybe this section is still helpful but just not clear?

**Comment by norosa** [comment]
@yuvaldrori if the concern here is that users accidentally run the script to link all their accounts, we could address that with additional warning text. How would you feel about that? I can land a new commit to do that for your review if you like?

**Comment by yuvaldrori** [comment]
@azure562 and @norosa we had a chat with Google after they had to credit a customer with 150k$ because of a customer losing a service account in a project they probably shouldn't have moved to our billing account. If they wouldn't move that project, they would be capped to 10k$ because it was using someones credit card. Google asked that we change the command to list only projects under the old billing account but I think the easiest course of action is to remove the multiple section because people don't read the docs and shoot themselves in the foot...

**Comment by yuvaldrori** [comment]
@norosa Are you going to approve this?

**Comment by norosa** [comment]
@yuvaldrori @azure562 and I plan to discuss this in the week and get back to you. Sorry for the delay.

**Review by azure562 — APPROVED** [review]

**Pull request merged**
