### PR TITLE
Add BQ Lens update time

### PR DESCRIPTION
**Pull request by azure562**
- Add a note about BQ Len update frequency
- Update screenshot

### CODE REVIEW

**Comment by mtagda** [comment]
@azure562 on BQ Lens dashboard there is one report widget and I am not sure about how often it is updated ( I think this is what the ticket you shared is about). Other components of the dashboard are updated daily. Not sure you want to somehow make it clear in the doc or just say it is updated daily?

**Review by norosa — APPROVED** [review]
Was the increase in screenshot size intentional? I'm still not exactly sure what we should be doing about screenshot sizes as we seem to be in a transitionary state, but I was wondering if 1200px wide (width specifically) is still a part of the guide we want to follow?

**Comment by azure562** [comment]
> @azure562 on BQ Lens dashboard there is one report widget and I am not sure about how often it is updated ( I think this is what the ticket you shared is about). Other components of the dashboard are updated daily. Not sure you want to somehow make it clear in the doc or just say it is updated daily?

@mtagda is it possible to find out how often that specific report widget is updated. I guess it's better to be clear to avoid future questions

**Comment by mtagda** [comment]
> > @azure562 on BQ Lens dashboard there is one report widget and I am not sure about how often it is updated ( I think this is what the ticket you shared is about). Other components of the dashboard are updated daily. Not sure you want to somehow make it clear in the doc or just say it is updated daily?
> 
> @mtagda is it possible to find out how often that specific report widget is updated. I guess it's better to be clear to avoid future questions

@azure562 this is a question to the Bruteforce team :) I don't know, honestly.

**Comment by norosa** [comment]
@azure562 ah! That explains it. I tried to recreate the logo issue myself but was unable to do so. I guess we can reevaluate once you've got a playground account. Weird that it would be dependent on that... Is it because of the size of the user account name in the top right-hand corner, or is it something else? 🤔

**Comment by azure562** [comment]
> > > @azure562 on BQ Lens dashboard there is one report widget and I am not sure about how often it is updated ( I think this is what the ticket you shared is about). Other components of the dashboard are updated daily. Not sure you want to somehow make it clear in the doc or just say it is updated daily?
> > 
> > 
> > @mtagda is it possible to find out how often that specific report widget is updated. I guess it's better to be clear to avoid future questions
> 
> @azure562 this is a question to the Bruteforce team :) I don't know, honestly.

@Dror88 @chaim0m any idea on this? :)

**Comment by Dror88** [comment]
> > > > @azure562 on BQ Lens dashboard there is one report widget and I am not sure about how often it is updated ( I think this is what the ticket you shared is about). Other components of the dashboard are updated daily. Not sure you want to somehow make it clear in the doc or just say it is updated daily?
> > > 
> > > 
> > > @mtagda is it possible to find out how often that specific report widget is updated. I guess it's better to be clear to avoid future questions
> > 
> > 
> > @azure562 this is a question to the Bruteforce team :) I don't know, honestly.
> 
> @Dror88 @chaim0m any idea on this? :)

There is no specific update time we can provide. It will usually be twice a day, the refresh time is going to be written in the widget menu starting today.

**Review by mtagda — APPROVED** [review]

**Pull request merged**
